name: Test

on: push

jobs:
  new-app:
    name: Create a new ember app
    runs-on: ubuntu-latest
    container: robert96/ember-js:latest

    steps:
      - name: Create a new app
        run: |
          ember new ember-app
          cd ember-app

      - name: Lint HBS files
        run: |
          npm run lint:hbs

      - name: Lint JS files
        run: |
          npm run lint:js

      - name: Test
        run: |
          ember test

      - name: Build
        run: |
          ember test