name: Test

on: push

jobs:
  new-app:
    name: Create a new ember app
    runs-on: ubuntu-latest
    container: robert96/ember-js:latest

    steps:
      - name: Create a new app
        run: |
          ember new ember-app

      - name: Lint HBS files
        run: |
          cd ember-app
          npm run lint:hbs

      - name: Lint JS files
        run: |
          cd ember-app
          npm run lint:js

      - name: Test
        run: |
          cd ember-app
          ember test

      - name: Build
        run: |
          cd ember-app
          ember test

  super-rentals:
    name: Test super-rentals example
    runs-on: ubuntu-latest
    container: robert96/ember-js:latest

    steps:
      - name: Clone the git repository
        run: |
          git clone https://github.com/ember-learn/super-rentals

      - name: Install NPM dependencies
        run: |
          cd super-rentals
          npm install

      - name: Lint HBS files
        run: |
          cd super-rentals
          npm run lint:hbs

      - name: Lint JS files
        run: |
          cd super-rentals
          npm run lint:js

      - name: Test
        run: |
          cd super-rentals
          ember test

      - name: Build
        run: |
          cd super-rentals
          ember test
